version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: insurance-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    image: insurance-backend:1.0
    container_name: insurance-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/insurance
    depends_on:
      - mongodb

  frontend:
    image: insurance-frontend:1.0
    container_name: insurance-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:

